export const agreementTokens = [
  "attachments_included",
  "authorized_operator_1",
  "authorized_operator_1_phone",
  "authorized_operator_2",
  "authorized_operator_2_phone",
  "consents_to_location_monitoring",
  "damage_waiver_accept",
  "damage_waiver_acknowledged",
  "damage_waiver_choice",
  "damage_waiver_decline",
  "damage_waiver_deductible",
  "damage_waiver_fee",
  "delivery_fee",
  "email",
  "extended_delivery_fee",
  "fuel_level_in",
  "fuel_level_out",
  "has_owner_permission",
  "hour_meter_in",
  "hour_meter_out",
  "is_property_owner_no",
  "is_property_owner_yes",
  "jobsite_address",
  "knows_boundaries",
  "knows_emergency_shutdown",
  "machine_serial",
  "machine_unit",
  "name",
  "not_digging_neighbor_property",
  "not_digging_public_row_without_permit",
  "owner_permission_no",
  "owner_permission_yes",
  "payment_reference",
  "phone",
  "received_quick_start_guide",
  "reservation_id",
  "security_deposit",
  "submitted_811_or_will_before_digging",
  "taxes",
  "ticket_811",
  "total_due",
  "tutorial_completion_status",
  "tutorial_video_version",
  "understands_basic_controls",
  "understands_equipment_may_be_tracked",
  "understands_fence_not_boundary",
  "understands_geofence_breach_consequences",
  "understands_private_utilities",
  "understands_tip_risk",
  "weekend_end",
  "weekend_rental_charge",
  "weekend_start",
  "will_avoid_utility_tolerance_zone",
  "will_call_if_unsure",
  "will_keep_people_pets_away",
  "will_not_move_without_approval",
  "will_not_tamper_with_tracking_device",
  "will_not_transport_without_approval",
  "will_not_undermine_structures",
  "will_stop_if_unsafe",
  "will_use_only_at_approved_jobsite",
  "will_wait_for_locate_window",
  "will_watch_tutorial_videos",
  "work_category",
  "work_description",
] as const;

export type AgreementToken = (typeof agreementTokens)[number];

const unresolvedTokenPattern = /\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g;

export function findUnresolvedAgreementTokens(text: string) {
  return Array.from(text.matchAll(unresolvedTokenPattern), (match) => match[1]);
}
